[package]
name    = "gossyp_base"
version = "0.1.0"
license = "MIT"
authors = ["Andrew Hunter <andrew@logicalshift.io>"]

[dependencies]
serde           = "1.0"
serde_json      = "1.0"
serde_derive    = "1.0"
